#GET http://localhost:4000/api/duplicates/email/mjmjmj

#GET http://localhost:4000/api/travel
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1NTE0MDExM30.SAnoYMJVL9oW-bXKyJnthyehBTvaJhIAEXIeEui3jeA
#DELETE http://localhost:4000/api/travels/5
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1NTE0MDExM30.SAnoYMJVL9oW-bXKyJnthyehBTvaJhIAEXIeEui3jeA
#POST http://localhost:4000/api/login
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1NTE0MDExM30.SAnoYMJVL9oW-bXKyJnthyehBTvaJhIAEXIeEui3jeA
#Content-Type: application/json
#
#{
#  "email": "test123@test.com",
#  "password": "qwer12345"
#}
#POST http://localhost:4000/api/signup
#Authorization:
#Content-Type: application/json
#
#{
#  "email":"test1234@test.com",
#  "nickname":"tttt1",
#  "password":"qwer12345",
#  "confirmPassword": "qwer12345"
#}
#PATCH http://localhost:4000/api/travels/6
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1NTE0MDExM30.SAnoYMJVL9oW-bXKyJnthyehBTvaJhIAEXIeEui3jeA
#Content-Type: application/json
#
#{
#  "title": "머냐고..",
#  "content": "먼데"
#}
POST http://localhost:4000/api/travels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1NTE0MDExM30.SAnoYMJVL9oW-bXKyJnthyehBTvaJhIAEXIeEui3jeA
Content-Type: application/json

{
  "title": "title",
  "content": "content"
}
